# Generated by Django 4.0.3 on 2022-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='defaultImage', upload_to='images'),
            preserve_default=False,
        ),
    ]
