# Generated by Django 4.0.3 on 2022-03-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_meetup_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=60)),
                ('fullAdress', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='defaultImage.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetups.location'),
        ),
    ]
