# Generated by Django 4.0.3 on 2022-03-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participant_meetup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='provAcronym',
            field=models.CharField(default='--', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2022-04-06'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizerEmail',
            field=models.EmailField(default='organizer-email-here@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetups.location'),
            preserve_default=False,
        ),
    ]
