# Generated by Django 4.0.3 on 2022-03-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_location_provacronym_meetup_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='fullAdress',
            new_name='fullAddress',
        ),
    ]
